spring:
  application:
    name: RocketMQ-Demo
#  config:
#    import: nacos:RocketMQ-Demo.yaml?refresh=true
#  cloud:
#    nacos:
#      config:
#        server-addr: 127.0.0.1:8848

server:
  port: 8099

io:
  cloudapp:
    messaging:
      rocketmq:
        enabled: true
        nameServer: ${ROCKET_HOST}
        username: ${ROCKET_USERNAME}
        password: ${ROCKET_PASSWORD}
        useTLS: false
        enableMsgTrace: true
        #        traceTopic:
#        inputs:
#          - group: test-group
#            #            accessChannel:
#            #            messageModel: CLUSTERING
#            #            pullBatchSize:
#            #            namespace:
#            name: rocketConsumer
#            topic: test-topic
        outputs:
          - name: rocketProducer
            #            messageModel: CLUSTERING
            group: test-group
#            namespace:
#            sendTimeout:
#            instanceName:
#            retryNextServer:
#            compressMsgBodyOverHowMuch:
#            maxMessageSize:
#            retryTimesWhenSendFailed:
