io:
  cloudapp:
    base:
      threadpool:
        enabled: true
        corePoolSize: 6
        maximumPoolSize: 9

spring:
  application:
    name: thread-pool-demo
  config:
    import: nacos:thread-pool-demo.yaml?refresh=true
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
#      discovery:
#        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
#        namespace: public
server:
  port: 18080