spring:
  application:
    name: filestore-aliyun-demo


io:
  cloudapp:
    filestore:
      aliyun:
        enabled: true
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
        endpoint: http://oss-cn-shenzhen.aliyuncs.com

server:
  port: 8080