spring:
  application:
    name: apigateway-aliyun-demo
  main:
    allow-bean-definition-overriding: true
io:
  cloudapp:
    apigateway:
      aliyun:
        enabled: true
        server:
          accessKey: ${AK}
          secretKey: ${SK}
          gatewayUri: ${brokerAddress}
#        groups:
#        support multi auth type,e.g. basic,apikey,jwt,oAuth2.
#        When multiple types are configured at the same time, only apikey will take effect.
#        apikey:
#          apiKey: ${apiKey}
#          headerName:  #default X-API-KEY
#        basic:
#          username: ${username}
#          password: ${password}
#        jwt:
#          keyId: ac1842b3ee2fbee3600
#          secret: test
#          issuer:
#          subject:
#          audience:
#          expiredSecond: 31536000
#          algorithm: HS256
        oAuth2:
          client-id: ${clientId}
          client-secret: ${clientSecret}
          redirect-uri: http://localhost:8080/oauth/code
          scopes:
            - openid
            - profile
          grant-types:
            - authorization_code
            - refresh_token
          authorization-uri: https://gitlab.com/oauth/authorize
          token-uri: https://gitlab.com/oauth/token
          jwks-url: https://gitlab.com/oauth/discovery/keys

