spring:
  application:
    name: aliee-demo
  cloud:
    prop: prop
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        import-check:
          enabled: false
        enabled: true
  config:
    import:
      - nacos:aliee-demo.yaml?refreshEnabled=true

server:
  port: 8083

