spring:
  application:
    name: ProducerDemo

io:
  cloudapp:
    messaging:
      kafka:
        servers: ${KAFKA_SERVER}
        username: ${KAFKA_USERNAME}
        password: ${KAFKA_PASSWORD}
        mechanism: PLAIN
        security-protocol: SASL_SSL
        #        identificationAlgorithm: ""
        ssl:
          trust-store-location: classpath:/sasl/mix.4096.client.truststore.jks
          trust-store-password: KafkaOnsClient
        outputs:
          - name: kafkaProducer
            group: test-group
            topic: test-topic
            properties:
              "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
          #              "allow.auto.create.topics": false
          - name: kafkaProducer2
            group: test-group
            topic: test-topic
            properties:
              "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
